### ISSUE TITLE
Not progressing 2 spaces when dice pairs equal and colored token on board

### ISSUE THREAD

**Issue by stphflwrs** [khaptonstall/Cant-Stop#1]
1. Be on 2 temporary tokens.
2. Have a colored token on the board where there is no temp token. (Say, 7)
3. Get a dice roll where both pairs are 7.
4. Choose that dice roll.
   Result: Move up one space instead of 2.

**Comment by khaptonstall** [comment]
Problem was in GameState.cpp in the validatePair(int,int,Player*) function. Fixed by adding the following line when the player's currentCols == 2:

``` c++
(find(p->currentCols.begin(), p->currentCols.end(), a) != p->currentCols.end() ||
                find(p->currentCols.begin(), p->currentCols.end(), b) != p->currentCols.end() || a == b)
```
